export * from "./LandingPage"
export * from "./InicioPage"
export * from "./ExperienciaPage"
export * from "./EstudiosPage"
export * from "./PortafolioPage"
export * from "./PerfilPage"
export * from "./ContactoPage"
